# Generated by Django 5.2.4 on 2025-07-18 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone_number', models.CharField(max_length=20)),
                ('job_title', models.CharField(max_length=100)),
                ('candidate_stage', models.CharField(max_length=100)),
                ('current_salary', models.DecimalField(decimal_places=2, max_digits=10)),
                ('expected_salary', models.DecimalField(decimal_places=2, max_digits=10)),
                ('years_of_experience', models.FloatField()),
                ('communication_skills', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=100)),
                ('source', models.CharField(max_length=100)),
                ('notes', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
