# Generated by Django 5.2.4 on 2025-07-24 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_chatsession_chatmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatsession',
            name='model',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
