# Generated by Django 5.2.4 on 2025-07-31 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_note'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chatmessage',
            options={'ordering': ['timestamp']},
        ),
        migrations.AlterModelOptions(
            name='chatsession',
            options={'ordering': ['-updated_at']},
        ),
        migrations.AlterModelOptions(
            name='jobpost',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='note',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='notification',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='content_compressed',
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='content_hash',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='is_compressed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='chatsession',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='chatsession',
            name='message_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddIndex(
            model_name='candidate',
            index=models.Index(fields=['email'], name='accounts_ca_email_ea1042_idx'),
        ),
        migrations.AddIndex(
            model_name='candidate',
            index=models.Index(fields=['created_at'], name='accounts_ca_created_82c217_idx'),
        ),
        migrations.AddIndex(
            model_name='candidate',
            index=models.Index(fields=['candidate_stage'], name='accounts_ca_candida_e62a0c_idx'),
        ),
        migrations.AddIndex(
            model_name='candidate',
            index=models.Index(fields=['job_title', 'created_at'], name='accounts_ca_job_tit_698741_idx'),
        ),
        migrations.AddIndex(
            model_name='chatmessage',
            index=models.Index(fields=['session', 'timestamp'], name='accounts_ch_session_a073b1_idx'),
        ),
        migrations.AddIndex(
            model_name='chatmessage',
            index=models.Index(fields=['session', 'role'], name='accounts_ch_session_12e7a4_idx'),
        ),
        migrations.AddIndex(
            model_name='chatmessage',
            index=models.Index(fields=['timestamp'], name='accounts_ch_timesta_ea2ba9_idx'),
        ),
        migrations.AddIndex(
            model_name='chatmessage',
            index=models.Index(fields=['content_hash'], name='accounts_ch_content_319886_idx'),
        ),
        migrations.AddIndex(
            model_name='chatsession',
            index=models.Index(fields=['user', 'created_at'], name='accounts_ch_user_id_cf8b49_idx'),
        ),
        migrations.AddIndex(
            model_name='chatsession',
            index=models.Index(fields=['user', 'is_active'], name='accounts_ch_user_id_5618b5_idx'),
        ),
        migrations.AddIndex(
            model_name='chatsession',
            index=models.Index(fields=['created_at'], name='accounts_ch_created_91cd04_idx'),
        ),
        migrations.AddIndex(
            model_name='chatsession',
            index=models.Index(fields=['updated_at'], name='accounts_ch_updated_b4fa24_idx'),
        ),
        migrations.AddIndex(
            model_name='city',
            index=models.Index(fields=['name'], name='accounts_ci_name_3741a5_idx'),
        ),
        migrations.AddIndex(
            model_name='communicationskill',
            index=models.Index(fields=['name'], name='accounts_co_name_7e58aa_idx'),
        ),
        migrations.AddIndex(
            model_name='jobpost',
            index=models.Index(fields=['status', 'created_at'], name='accounts_jo_status_188506_idx'),
        ),
        migrations.AddIndex(
            model_name='jobpost',
            index=models.Index(fields=['employment_type'], name='accounts_jo_employm_24d75c_idx'),
        ),
        migrations.AddIndex(
            model_name='jobpost',
            index=models.Index(fields=['location'], name='accounts_jo_locatio_e355ae_idx'),
        ),
        migrations.AddIndex(
            model_name='jobpost',
            index=models.Index(fields=['posted_by', 'created_at'], name='accounts_jo_posted__2686f6_idx'),
        ),
        migrations.AddIndex(
            model_name='jobtitle',
            index=models.Index(fields=['name'], name='accounts_jo_name_f28cae_idx'),
        ),
        migrations.AddIndex(
            model_name='note',
            index=models.Index(fields=['candidate', 'created_at'], name='accounts_no_candida_4d66f2_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['user', 'is_read'], name='accounts_no_user_id_a4ff2e_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['created_at'], name='accounts_no_created_caf92d_idx'),
        ),
        migrations.AddIndex(
            model_name='source',
            index=models.Index(fields=['name'], name='accounts_so_name_1de8aa_idx'),
        ),
    ]
